import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import heroImg from '../assets/hero.png';
import '../styles/WelcomePage.css';

const WelcomePage = () => {
  const navigate = useNavigate();
  const [loadingText, setLoadingText] = useState("Analyzing learning patterns...");
  const [fadeClass, setFadeClass] = useState('fade-in');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const phrases = [
      "Analyzing learning patterns...",
      "Preparing your AI tutor...",
      "Building personalized study journey..."
    ];

    // Sequential phrase timer setups
    // Phrase 1 (Analyzing...) fades out at 600ms
    const t1 = setTimeout(() => setFadeClass('fade-out'), 600);
    
    // Phrase 2 (Preparing...) fades in at 800ms
    const t2 = setTimeout(() => {
      setLoadingText(phrases[1]);
      setFadeClass('fade-in');
    }, 800);

    // Phrase 2 fades out at 1400ms
    const t3 = setTimeout(() => setFadeClass('fade-out'), 1400);

    // Phrase 3 (Building...) fades in at 1600ms
    const t4 = setTimeout(() => {
      setLoadingText(phrases[2]);
      setFadeClass('fade-in');
    }, 1600);

    // Phrase 3 fades out at 2200ms
    const t5 = setTimeout(() => setFadeClass('fade-out'), 2200);

    // End loading and reveal main welcome content at 2400ms
    const t6 = setTimeout(() => {
      setIsLoading(false);
    }, 2400);

    return () => {
      clearTimeout(t1);
      clearTimeout(t2);
      clearTimeout(t3);
      clearTimeout(t4);
      clearTimeout(t5);
      clearTimeout(t6);
    };
  }, []);

  const handleStart = () => {
    navigate('/login');
  };

  return (
    <div className="welcome-wrapper">
      {isLoading ? (
        <div className="loading-container" style={{ flexDirection: 'column', gap: '2rem' }}>
          <div className="loading-spinner">
            <div className="spinner-outer"></div>
            <div className="spinner-inner"></div>
            <div className="spinner-glow"></div>
          </div>
          <div className={`loading-text ${fadeClass}`}>
            {loadingText}
          </div>
        </div>
      ) : (
        <div className="center-container">
          {/* SECTION 1: Illustration Area */}
          <div className="section-illustration animate-fadeInUp delay-1">
            <div className="glow-backdrop"></div>
            <img src={heroImg} alt="AI Education" className="floating-illustration" />
          </div>

          {/* SECTION 2: Application Name */}
          <div className="section-app-name animate-fadeIn delay-2">
            NeuroLearn AI
          </div>

          {/* SECTION 3: Main Heading */}
          <h1 className="section-heading animate-fadeInUp delay-3">
            Your Personal AI Learning Companion
          </h1>

          {/* SECTION 4: Description */}
          <p className="section-description animate-fadeIn delay-4">
            Analyze your strengths, identify weak concepts, track your progress, 
            and receive personalized learning plans generated by AI.
          </p>

          {/* SECTION 5: Primary Button */}
          <div className="section-action animate-fadeInUp delay-5">
            <button className="primary-button" onClick={handleStart}>
              GET STARTED
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default WelcomePage;
